- draft-ietf-httpbis-semantics-latest.xml
> Clarify about early responses

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Move "Associating a Response to a Request" to Messaging.

- draft-ietf-httpbis-semantics-latest.xml
> Reserve 418 status code

- draft-ietf-httpbis-cache-latest.xml
> Expand "History Lists" to "Relationship to Applications".

- draft-ietf-httpbis-cache-latest.xml
> Revise Sending a Validation Request

- draft-ietf-httpbis-cache-latest.xml
> Clarify no-store/etc and multiple requests

- draft-ietf-httpbis-cache-latest.xml
> Only final responses are cacheable

- Makefile
- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
- httpbis.abnf
> Obsolete Warning

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Rework 2.1 Client/Server Messaging to be more version-independent

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Make request cache-control advisory

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
- lib/extract-header-defs.xslt
> Establish a separate header registry

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
Fixes #46.
(alternative approach)
> Rearrange conneg and talk about *

- draft-ietf-httpbis-messaging-latest.xml
> Caution against treating data on a connection as part of a not-yet-issued request

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> Obsolete Content-MD5

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> remove misleading text for HTTP extension needed for OPTIONS payloads

- draft-ietf-httpbis-semantics-latest.xml
> Consolidate sections on new header names and values

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Move version non-specific parts of message body into semantics

- draft-ietf-httpbis-cache-latest.xml
> Describe Vary operation more clearly (Mnot 28)

- draft-ietf-httpbis-semantics-latest.xml
> Alternative Services (Mnot 143)

- draft-ietf-httpbis-semantics-latest.xml
> Move "Whitespace" into "Generic Syntax"

- draft-ietf-httpbis-cache-latest.html
- draft-ietf-httpbis-cache-latest.xml
pasted twice, second should have been s-maxage
> fix #264 must-revalidate paste-o

- draft-ietf-httpbis-cache-latest.xml
Fixes #268
I think this is the right thing to do; we added too much text here in 7234.
> Constrain CC public and private

- draft-ietf-httpbis-semantics-latest.xml
.. moving text to more appropriate places.
> Rearrange considerations for new fields

- draft-ietf-httpbis-semantics-latest.xml
> Clarify that request bodies on DELETE are not interoperable

- draft-ietf-httpbis-semantics-latest.xml
> Give guidance on interoperable field names

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> Define semantics and acceptable replacement of WS

- draft-ietf-httpbis-cache-latest.xml
> Clarify that any "*" as a member of Vary will disable caching

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Clarify language regarding CC: private

- draft-ietf-httpbis-semantics-latest.xml
> recommend comma SP when combining field lines

- draft-ietf-httpbis-semantics-latest.xml
> Give an example of new field terminology

- draft-ietf-httpbis-semantics-latest.xml
I didn't update the HTML, because the Makefile relies on Java.  I'm not installing Java just for this; sorry.
> Missing fields

- draft-ietf-httpbis-cache-latest.xml
> Clarify public and private

- draft-ietf-httpbis-semantics-latest.xml
> HTTP/1.1 -> HTTP

- draft-ietf-httpbis-semantics-latest.xml
> CONNECT forwards data, not packets

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> Describe scope concerns for extensions

- draft-ietf-httpbis-semantics-latest.xml
> Present If-[none]-Match evaluation more clearly

- draft-ietf-httpbis-semantics-latest.xml
> Specify scope of Proxy-Auth*

- Makefile
- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
- lib/extract-cache-directives.xslt
- lib/extract-header-defs.xslt
- lib/extract-status-code-defs.xslt
Text taken from existing statement in Location.
Fixes #321.
> Add note about URL resolution to C-L and Referer

- draft-ietf-httpbis-semantics-latest.xml
> remove request-line and status-line from Semantics

- draft-ietf-httpbis-semantics-latest.xml
> Move Date/Time formats

- draft-ietf-httpbis-semantics-latest.xml
I got distracted by old text and revised the introduction of semantics.
> revise introduction for HTTP family of protocols; addresses #64

- draft-ietf-httpbis-semantics-latest.xml
> 'Host header field' is redundant

- draft-ietf-httpbis-semantics-latest.xml
incorporate suggestions from @mnot and @martinthomson
> tweak introduction as per comments on #416; fixes #64

- draft-ietf-httpbis-semantics-latest.xml
> new content codings ought to be self-descriptive

- draft-ietf-httpbis-semantics-latest.xml
> Talk about BREACH

- draft-ietf-httpbis-semantics-latest.xml
> Talk about multiple WWW-Authenticate values

- draft-ietf-httpbis-semantics-latest.xml
> Allow preconditions to be evaluated before processing the request body

- draft-ietf-httpbis-semantics-latest.xml
> Allow for multiple trailer sections and define iterative processing

- draft-ietf-httpbis-cache-latest.xml
> Re-order Invalidation

- draft-ietf-httpbis-cache-latest.xml
> Remove spurious "UTC"

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
And mention in Semantics.
Fixes #473.
> Correct rules considered case-insensitive in dates

- draft-ietf-httpbis-cache-latest.xml
> Clarify Age error handling

- draft-ietf-httpbis-cache-latest.xml
> Clarify req on storing full response to conditional

- draft-ietf-httpbis-cache-latest.xml
> Clarify duplicate and invalid freshness info

- draft-ietf-httpbis-semantics-latest.xml
> Define implicit and explicit framing without detailing the mechanisms

- draft-ietf-httpbis-semantics-latest.xml
> 1xx language about bodies and trailers

- draft-ietf-httpbis-semantics-latest.xml
> Explain that 206 responses can be a subset of the requested ranges

- draft-ietf-httpbis-cache-latest.xml
> Tighten up Vary language

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
... with associated adjustments
Fixes #444
> HTTP/1.1 Messaging -> HTTP/1.1

- draft-ietf-httpbis-semantics-latest.xml
> Introduce protocol versioning and messages

- draft-ietf-httpbis-semantics-latest.xml
> Remove Control Data

- draft-ietf-httpbis-semantics-latest.xml
> Introductory text for 'authoritative access'

- draft-ietf-httpbis-semantics-latest.xml
> Rename 'Framing' and move it up

- draft-ietf-httpbis-messaging-latest.xml
> Remove history overview that is now in Semantics

- draft-ietf-httpbis-semantics-latest.xml
> Say a bit more about PUT handling

- draft-ietf-httpbis-semantics-latest.xml
> improve message abstraction to reflect semantics after message is parsed

- draft-ietf-httpbis-semantics-latest.xml
> add :authority pseudo-header to Host discussion and make section applicable to both

- draft-ietf-httpbis-semantics-latest.xml
> update references to other security considerations

- draft-ietf-httpbis-semantics-latest.xml
> simplify security consideration on confidentiality of credentials

- draft-ietf-httpbis-semantics-latest.xml
by changing DL to a table and tweaking description of HEAD. Fixes #572
> clarify the payload in 200 (OK)

- draft-ietf-httpbis-semantics-latest.xml
> improve abstract

- draft-ietf-httpbis-semantics-latest.xml
> remove old organization intro text and update headings (editorial)

- draft-ietf-httpbis-cache-latest.xml
> Clarify must-revalidate error response

- draft-ietf-httpbis-semantics-latest.xml
Fixes #618.
Note outstanding question on the issue regarding PUT.
> Ignore content-range in requests

- draft-ietf-httpbis-semantics-latest.xml
Including a re-org of Considerations for New Fields
Fixes #539.
> Mention Structured Fields

- draft-ietf-httpbis-semantics-latest.xml
Fixes #622 
This is an attempted recovery of the prematurely merged pull request that left us in a bad state.
> import 421 (Misdirected Request) Status Code from h2 again

- draft-ietf-httpbis-semantics-latest.xml
Commas were a bit overwhelming
> Tweak core semantics

- draft-ietf-httpbis-semantics-latest.xml
> Cache can't be used when acting as a tunnel

- draft-ietf-httpbis-semantics-latest.xml
> Tweak abstract

- draft-ietf-httpbis-semantics-latest.xml
> Remove 'captive portal'

- draft-ietf-httpbis-semantics-latest.xml
> mention request target forms in considerations for new methods

- draft-ietf-httpbis-cache-latest.xml
> Mention INM/IMS precedence

- draft-ietf-httpbis-cache-latest.xml
> Modify must-understand to be backwards-compatible

- draft-ietf-httpbis-cache-latest.xml
> Clarify how multiple validators are handled

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Invalid Date handling

- draft-ietf-httpbis-semantics-latest.xml
> Specify IMS and IUS like INM and If-Match

- draft-ietf-httpbis-semantics-latest.xml
I know that this is pretty obvious and implied, but maybe it's worth saying.
> TE: trailers is in a request

- draft-ietf-httpbis-semantics-latest.xml
…levant when some of the acceptable ones are redundant (fixes #714)
> Clarify that selection between multiple acceptable codings is only relevant when some of the acceptable ones are redundant (fixes #714)

- draft-ietf-httpbis-semantics-latest.xml
I wasn't sure where exactly to include the citation, but the end of the sentence seemed harmless.
> Cite conditional requests in 412 definition

- draft-ietf-httpbis-semantics-latest.xml
> Use overwrite rather than "white out"

- draft-ietf-httpbis-messaging-latest.xml
> Clearer requirements about delineation of requests

- draft-ietf-httpbis-cache-latest.xml
> Broaden cache poisoning

- draft-ietf-httpbis-messaging-latest.xml
> rephrase connection closure incomplete (editorial)

- draft-ietf-httpbis-semantics-latest.xml
> Move discussion of statelessness

- draft-ietf-httpbis-messaging-latest.xml
> Explicitly close the connection

- draft-ietf-httpbis-semantics-latest.xml
> Method semantics are inviolate

- draft-ietf-httpbis-semantics-latest.xml
> No need to explain why From is bad

- draft-ietf-httpbis-semantics-latest.xml
> Remove Canonicalization and Text Defaults

- draft-ietf-httpbis-semantics-latest.xml
> Mention payload -> content change

- draft-ietf-httpbis-semantics-latest.xml
> Discuss forwarding and extensibility

- draft-ietf-httpbis-cache-latest.xml
> Clarify what cache proxy considerations apply to

- draft-ietf-httpbis-semantics-latest.xml
> An upgraded protocol starts after the 101 response

- draft-ietf-httpbis-semantics-latest.xml
> Refine Referer

- draft-ietf-httpbis-cache-latest.xml
> Adjust handling of invalid Age values

- draft-ietf-httpbis-cache-latest.xml
> Mention relaxation of reqs for parsing Expires

- draft-ietf-httpbis-semantics-latest.xml
> Be consistent about content[- ]coding

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Remove mid-stream trailers

- draft-ietf-httpbis-semantics-latest.xml
> simplify description of reactive content negotiation (editorial)

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Change HTTP messages to <sourcecode>

- draft-ietf-httpbis-semantics-latest.xml
> Clarify normalisation 

- draft-ietf-httpbis-semantics-latest.xml
> Explicitly require TE to be listed in Connection

- draft-ietf-httpbis-semantics-latest.xml
> Clarify status of data after CONNECT headers

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> Note that Trailer isn't hop-by-hop

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> provide a definition for the close connection option under 1.1 tear-down

- draft-ietf-httpbis-semantics-latest.xml
Fixes #715 without changing section numbering
> clarify extensibility of preconditions

- draft-ietf-httpbis-semantics-latest.xml
I think this looks better and will stand the test of time.
> tweak the Acks to remove me

- writeup/cache.md
This assumes that the editors will correctly report that they are in
compliances with the IPR disclosure rules.
> Writeup for cache

- draft-ietf-httpbis-cache-latest.xml
> Selected Representations and Validating Requests

- draft-ietf-httpbis-semantics-latest.xml
> TCP -> underlying transport

- draft-ietf-httpbis-semantics-latest.xml
> Reinstate 'to a request' in 206

- draft-ietf-httpbis-semantics-latest.xml
> remove "TCP"

- draft-ietf-httpbis-semantics-latest.xml
> Explain the "Content-" prefix

- draft-ietf-httpbis-semantics-latest.xml
> Align field name requirements

- draft-ietf-httpbis-messaging-latest.xml
> Feedback from Lars

- draft-ietf-httpbis-semantics-latest.xml
Fixes #896.
Note that if we go in this directions, there are some editorial improvements in #897 that we should pull in separately.
> Check target URIs for scheme semantic mismatches

- draft-ietf-httpbis-cache-latest.xml
> Clarify that only selectable responses are updated

- draft-ietf-httpbis-semantics-latest.xml
Replaces #870 by @kaduk (minus the bits already committed) with adjustments by me.
> forked suggestions by kaduk with further edits

- draft-ietf-httpbis-semantics-latest.xml
> address remaining Roman Danyliw editorial comments

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
- httpbis.abnf
- lib/abnf2xml2rfc.xslt
- lib/common-abnf.sh
> switch to named references instead of RFC numbers (for HTTP family)

- draft-ietf-httpbis-messaging-latest.xml
> clarify ordering of outstanding requests

- draft-ietf-httpbis-semantics-latest.xml
> Clarify that a false If-Range means ignore the Range

- draft-ietf-httpbis-semantics-latest.xml
> Re-introduce what to do without a mod date

- draft-ietf-httpbis-semantics-latest.xml
> explicitly refer to how this spec defines access to http or https resources

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
> make clock a defined term and use it as such

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> use chosen response instead of selected response and avoid selected resource

- draft-ietf-httpbis-semantics-latest.xml
> slight editorial tweaks to Connection

- draft-ietf-httpbis-cache-latest.xml
> Correct use of 'body' and 'payload'
