httpwg/http-core

- draft-ietf-httpbis-cache-latest.xml
Fixes #140.
Note that there's one more reference to pragma remaining, but that will be taken care of by #171.
> Deprecate Pragma

- draft-ietf-httpbis-semantics-latest.xml
> clarify when header field combination is allowed

- draft-ietf-httpbis-messaging-latest.html
- draft-ietf-httpbis-messaging-latest.xml
- httpbis.abnf
This one is almost trivial. Except:
- previously, the ABNF sort-of ruled out parameters in the ABNF (at least that was the intent)
- this is now done in prose - we need to say though what to do when parameters *are* present - is "SHOULD treat as error" correct?
> transfer-coding: remove the predefined codings from the ABNF and make  it generic instead (see #66)

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
(also adds two paragraph breaks)
> Be more correct about what was deprecated by RFC 3986 (and also talk about https URIs) (#278)

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
Does not address Vary (see #286), and some more discussion of some of the conditional request headers might be warranted.
Fixes #289.
> Consistent language about list-based headers

- draft-ietf-httpbis-semantics-latest.xml
- Explicitly nominate range units as case insensitive
- Normalise how we talk about case sensitivity of extension points:
- right next to the ABNF
- combine with statement encouraging registration
Fixes #179.
> Case insensitivity for extension points

- draft-ietf-httpbis-semantics-latest.html
- draft-ietf-httpbis-semantics-latest.xml
add cross references to clarify that Range works on representation data and that such data might have a content coding; fixes #11
> add cross references to clarify that Range works on representation data

- draft-ietf-httpbis-semantics-latest.xml
> Don't rely on the HTTP/1.1 Messaging specification to define "message"

- draft-ietf-httpbis-semantics-latest.xml
> Remove H1-specific connection-related requirements

- Makefile
Currently we have about 110+ characters per line;
broadly accepted norms for readability are 55-65.
This takes it to about 85.
> Make text body narrower for readability

- draft-ietf-httpbis-messaging-latest.xml
> Don't claim Transfer-Encoding is in HTTP/2.

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
changes to -messaging pulled from https://github.com/httpwg/http-core/pull/373
> Prohibit bare CRs in header section

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Prohibit bare CRs in field values and sections.

- draft-ietf-httpbis-semantics-latest.xml
based upon existing requirement in evaluation.
I think this is editorial, because it's just referencing an already-existing requirement there.
Fixes #358.
> Qualify requirement on applying conditionals

- draft-ietf-httpbis-semantics-latest.xml
this is the part of https://github.com/httpwg/http-core/pull/373 related to -semantics
> prohibit vertical whitespace in field values (#377)

- draft-ietf-httpbis-semantics-latest.xml
... for If-Match and If-None-Match.
Fixes #305.
> State that multiple "*" has no defined semantics

- draft-ietf-httpbis-semantics-latest.xml
In 416 status code section, remove duplicate definition of what makes a range satisfiable and refer instead to each range unit's definition. In sections on bytes ranges and Range, clarify that a selected representation of zero length can only be satisfiable as a suffix range and that a server can still ignore Range for that case.
Fixes #12
> Clarify Range request on a zero-length representation

- draft-ietf-httpbis-semantics-latest.xml
Note that I decided to switch to text/plain (and format parameter), for consistency with the preceding text in that section.
> Avoid use of obsolete media type parameter on text/html (#375)

- draft-ietf-httpbis-semantics-latest.xml
- lib/extract-header-defs.xslt
- lib/extract-method-defs.xslt
- lib/extract-status-code-defs.xslt
did I mention that I hate line breaks in text table crossrefs?
This makes the text format much better, but the html output is worse because the stylesheet isn't padding cells. I am hoping that would be a simple fix.
> make section xrefs in tables more concise and consistent (editorial)

- draft-ietf-httpbis-semantics-latest.xml
- httpbis.abnf
(this is a regression from #408 )
> fix parameter ABNF for "expect" - broken by previous change (#203)

- draft-ietf-httpbis-semantics-latest.xml
evaluating false on a duplicate change request sending 2xx without validator for reasons unknown.
Fixes #166
> remove edge case requirement for If-Match and If-Unmodified-Since

- draft-ietf-httpbis-cache-latest.xml
> Define request collapsing

- draft-ietf-httpbis-cache-latest.xml
Now that we have three different places referring to the text on updating stored headers, it deserves its own section.
In the process, I noticed that the current text forgot to mention that CC: private and no-cache can have arguments that affect header storage.
Fixes #458.
> Factor out Updating Stored Headers and use in Combining Responses

- draft-ietf-httpbis-semantics-latest.xml
> Adjust section titles

- draft-ietf-httpbis-cache-latest.xml
> Refine text about application caches

- draft-ietf-httpbis-semantics-latest.xml
and only define the versioning there; leave message version requirements in control data.
(no content changes)
> move protocol version section up to conformance

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
This eliminates confusion with the message body protocol element of HTTP/1.1 and other usage of multipart body parts, and should make it easier to describe HTTP/2 and HTTP/3 data frames.
Fixes #553
> use payload or payload data for semantics instead of body or body data

- draft-ietf-httpbis-semantics-latest.xml
Fixes #565 
initial commit is just moving sections and updating headings;
second commit will update some of "the following" comments to refer to the specific fields.
> rearrange content negotiation so that all fields are at end

- draft-ietf-httpbis-semantics-latest.xml
fixes #559 
Note that I also cleaned up the surrounding paragraph and removed parentheses from around the statement that the response always terminates after the header section.
> clarify definition of HEAD and why some header fields differ in response

- draft-ietf-httpbis-semantics-latest.xml
Replace the term "partial request" with "range request".
The terminology "partial request" has not been defined in this document.
> Replace "partial request" with "range request"

- draft-ietf-httpbis-messaging-latest.xml
> Clarify that intermediary can forward dual TE and CL message after removing CL and processing TE

- draft-ietf-httpbis-cache-latest.xml
We use colons above to delimit conditionals in the list
> , -> : (for consistency)

- draft-ietf-httpbis-semantics-latest.xml
... as we use them to delimit strings elsewhere.
> Use double quotes

- draft-ietf-httpbis-cache-latest.xml
avoids repeating 'transfers' with different meanings
> transfers -> transmission

- draft-ietf-httpbis-cache-latest.xml
so it's adjacent to the other range-related requirements, rather than separated from them by the authenticated requirements.
> Move 'combining partial content' up

- draft-ietf-httpbis-semantics-latest.xml
> parse defensively instead of requiring an untestable reasonableness

- draft-ietf-httpbis-cache-latest.xml
Fixes #657
Note that this doesn't address the case of how a recipient should behave if Date is present, but doesn't parse. That would require changing Semantics too, which I'm inclined to do (to also use the message receipt time in this case). Thoughts?
> Clarify how caches handle missing Date

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
Fixes #654
and makes the whole spec read a lot easier because now the major feature names align with the content of a message.
> Use the term content instead of payload

- draft-ietf-httpbis-semantics-latest.xml
> provide a definition for partial PUT

- draft-ietf-httpbis-cache-latest.xml
... it's just deployments of very very old caches that would be of concern here.
Given how unlikely this is in 2020, how broken they would be for other reasons, and the
prevalence of HTTPS, it seems safe to modify these statements.
Fixes #660.
> Even HTTP/1.0 caches now support Age and CC

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
> Rework representations

- draft-ietf-httpbis-semantics-latest.xml
But then it has an example that contradicts this.
> The document recommends putting Basic first

- draft-ietf-httpbis-semantics-latest.xml
This isn't a place for equivocation.
This could have been MUST except that that isn't good to use here.
I considered just "conforms to" as well.  That would also work, but that is
incompatible with "wishes to" and I was less confident in removing that.  I
could do "conforms to" with "gateway that interoperates with inbound HTTP
servers", but that's a bigger change.
> Remove 6919 language

- draft-ietf-httpbis-semantics-latest.xml
The expression used here implies that a content-type is a function that
converts "bits" into a sequence of octets.  That doesn't match with my
understanding, as a content type is an encoding of some abstract data, which
might not be a linear construct, into representation data that can be
expressed in a protocol like HTTP.
I considered "abstract data", but that breaks line limits.  This seems like
a reasonable compromise.
> A content-type converts abstract data into bits

- draft-ietf-httpbis-semantics-latest.xml
In the definition of the https scheme, the phrase "strong encryption" is used.
This implies some sort of judgment.  I think that the key is that both
client and server need to agree on the adequacy of the protections.  Noting
that this might be contextual is somewhat obvious at that point, but I thought
it might be worth pointing out that what is generally acceptable might change
over time.
> Try to better define "strong" encryption

- draft-ietf-httpbis-semantics-latest.xml
This is how it works in practice.
RFC 6125 is due for an update, I guess.  iPAddress subjectAltName has been
supported for years and years, but it never managed to capture it properly.
This is definitely a big change in that it now outlaws CN-ID.  And the
definition of IP-ID here is probably overreach, but I don't see how we can
avoid that.  I don't want to update RFC 6125 here (as much as it needs
updating), so making the definition standalone seemed like the right way to
handle it.
Closes #680.
> IP address reference identities

- draft-ietf-httpbis-messaging-latest.xml
I didn't want to make this too disruptive, so I concentrated on the high
points.  Related to the changes in #734.
Breakdown:
- integrity is important (existing text)
- HTTPS provides integrity, but you have to be careful with truncation
(includes existing example)
- HTTP provides no integrity
- extensions can be used to provide additional protection, including
managing the risk of intermediaries messing around (massaging existing
text)
Closes #726.
> Attempt a rewrite of message integrity text

- draft-ietf-httpbis-messaging-latest.xml
1. A response is incomplete if the TLS connection close was incomplete.
2. Remove text about TLS reuse/resumption, which was very inconsistent.
On the first, I removed a case of "partial closure" rather than "incomplete
closure".  I also linked the incomplete message handling section with the TLS
connection closure section.
> Fixes for TLS connection closure

- draft-ietf-httpbis-cache-latest.xml
> Define 'cache key'

- draft-ietf-httpbis-semantics-latest.xml
> Be more explicit about Content-Length errors

- draft-ietf-httpbis-semantics-latest.xml
> Reject CONNECT requests without a port

- draft-ietf-httpbis-semantics-latest.xml
The original text here sort of implied that it was enough for an origin server
to just send 2xx.  That assumed that the request was for the origin server
itself and elided a bunch of detail.  This is shorter and clearer, I think.
> Origin servers might support CONNECT

- draft-ietf-httpbis-semantics-latest.xml
> A CONNECT tunnel starts after the response header section

- draft-ietf-httpbis-messaging-latest.xml
> Refine version requirement for intermediaries

- draft-ietf-httpbis-semantics-latest.xml
When the text suggests that credentials can be automatically applied to all
requests made within a protection space, that begs the question: how do I know
what requests are in the same protection space?
The answer is "well, you don't really".  Authentication schemes might define
something, but otherwise you are left to guess.  This PR says that as directly
as I could manage.
I considered adding another sentence here that says "In the absence of
specific information about the extent of a protection space, clients &MAY;
assume that the protection space extent is the origin of the server."  I'd
like thoughts on whether that is helpful.  I think that it might be, as otherwise
this isn't really implementable.
Closes #710.
> The extent of a protection space is unknowable

- draft-ietf-httpbis-semantics-latest.xml
> Restore recipient requirements for invalid characters in field values

- draft-ietf-httpbis-semantics-latest.xml
> Remove TRACE requirement on message/http media type (last normative ref to HTTP/1.1)

- draft-ietf-httpbis-messaging-latest.xml
The section was talking about server load as well, but it doesn't mention that
being a cost of closing connections.
> Network congestion or server load

- draft-ietf-httpbis-messaging-latest.xml
- httpbis.abnf
> use uri-host:port to define the authority form

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
... components, depending on the form of request-target, and when authority might be empty.
Fixes #722
This is an alternative to #732
> clarify how the target URI is extracted from 1.1 request

- draft-ietf-httpbis-semantics-latest.xml
Though I think that this text is correct, an HTTP/3 response only ends when
the stream is closed, not at the end of the header section.  I think that it's
not necessary to say this bit anyway.
> How a HEAD response terminates is version-specific

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
this is only editorial, but worth reviewing first.
> use active instead of passive voice and introduce status code classes before requirements

- draft-ietf-httpbis-semantics-latest.xml
> Application handling of field names

- draft-ietf-httpbis-cache-latest.xml
replaces #874 with my own edits.
Note that I added "without revalidation" to the description of Vary since the cache can use the stored response, regardless of Vary, once it has been revalidated by the origin server (e.g., 304 with etag).
> (editorial) tweaks inspired by kaduk suggestions from IESG review

- draft-ietf-httpbis-messaging-latest.xml
This is related to the suggestion in #872 but provides the modern reason why all servers work this way.
> (editorial) remove bit about accepting absolute-form for potential transition

- draft-ietf-httpbis-semantics-latest.xml
- httpbis.abnf
Clarify that Accept-Ranges can be sent by any server, remove "none" from the ABNF because it is now a reserved range unit, and allow the field to be sent in a trailer section while noting why that is much less useful than as a header field
For #857 
this is an alternative to #882
> clarify that Accept-Ranges can be sent by any server

- draft-ietf-httpbis-semantics-latest.xml
Fixes #934 
This works well on multiple levels because these fields are not about the request or response context, but rather about the message itself. Date is now defined early and close to the date value definitions of 5.6.7. Trailer is now defined just after the description of trailers. Also, it avoids changing any xrefs from HTTP/3.
Only the section heading and intro are new -- the moved text has not been changed.
> move Date and Trailer to a new (last) subsection of Message Abstraction

- draft-ietf-httpbis-cache-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
Move requirements on status codes to where they will be seen.
Move requirements on cache validation to where cache validation is defined.
Update both for the (slightly newer) If-Range.
This is mostly editorial but rephrases some existing requirements.
fixes #933
> split when to use validators into other sections

- draft-ietf-httpbis-messaging-latest.xml
- draft-ietf-httpbis-semantics-latest.xml
… (now entirely handled by HTTP/1.1 messaging).
Include LF in discussion of what characters are invalid in field values.
Require obs-fold to be processed when consuming message/http data.
fixes #923
> remove mention of obs-fold line folding from semantics

- draft-ietf-httpbis-semantics-latest.xml
It may or may not be useful to have an HTTP extension in order to
perform reactive negotiation -- one possible approach that does not
require an extension would be policy in the user-agent.
In the spirit of "less is more", and to not overly constrain our
forward-looking statement, just remove the phrase "as an extension".
(inspired by follow-up discussions on #914)
> Wordsmith future guidance on reactive negotiation

- draft-ietf-httpbis-semantics-latest.xml
Inspired by some discussion on #914 : while just the word "security"
is indeed used in marketing literature for proxies, it's meaning to different
parties is so varied so as to not really convey much useful information.  In the
IETF we try hard to be clear about what security provides we need and/or provide,
avoiding the vague catch-all term.  However (as I am reminded out of band), the
audience of this document is not exactly security experts, and it is easy to go
overboard trying to be precise, at least in this instance.
[actual commit message body retained below]
The mere act of inserting a proxy into the chain does not, in and of
itself, do much of anything for the security of the system (and a badly
implemented proxy can make the security of the system much worse).
A proxy can, …
> Avoid bare 'for the sake of security'

- draft-ietf-httpbis-semantics-latest.xml
The follow-up discussion on #914 indicated that the nature of the updates to RFC 3864 is essentially a "partial obsoletes", which means that we do not want to be part of BCP 90 even if we could -- we're carving off a piece of it and branching out on our own.  This PR attempts to reword the description slightly to indicate that we're not just tweaking part of RFC 3864, but rather replacing part of it (the parts that relate to HTTP), hopefully without bloating the text too much.
> Wordsmith the discussion of RFC 3864 updates

- draft-ietf-httpbis-messaging-latest.xml
Inspired by my ballot comments (#915 )
I started trying to write something about how it's required to send "close_notify" in normal connection shutdown, but didn't like how that worked, and ended up here.
I am not sure if I regressed in some other axes while improving on this one, though.
> Wordsmith the TLS secure close depiction

- draft-ietf-httpbis-semantics-latest.xml
Inspired by follow-up discussions on #914 , make a concrete proposal for how the RFC 3986 security considerations might be mentioned in our own security considerations.
I understand the editors' stance on adding substantial new text at this point, and will defer to them on whether this constitutes "substantial".
> strawman for referencing the URI security considerations

- draft-ietf-httpbis-semantics-latest.xml
The current text of "ought to ... where possible" is easy to read
as saying "if you have the technical capability, do it".
There are, however, some subtleties, such as if you get the 308 response
over http-not-s, in which case the question of whether or not to
re-link is not so clear-cut.
Change from "where possible" to "where appropriate" to hint that there
is some logic needed here beyond "blindly accept".
(inspired by follow-up discussions from #914)
> wordsmith automatic-link-editing guidance

- draft-ietf-httpbis-semantics-latest.xml
Fixes #1011 
This is longer than I wanted but has the benefit of defining a satisfiable ranges-specifier in general (instead of only for bytes requests), how to handle an invalid ranges-specifier as a bad request, and defines which code to use for an unsupported range-unit.
I believe all of this was implied by the existing text and how we have used valid/invalid, but I think it is clearer stated this way instead of the prior generalizations.
YMMV. This probably should be reviewed by the WG (just to be sure).
> clarify handling of invalid or unsatisfiable range requests
